### ISSUE TITLE
Disqus 기능 추가 

### ISSUE THREAD

**Issue by ssunno** [tmaxai/tmaxai.github.io#12]
Disqus에 tmaxai 계정 만들고 연동하기

post 레이아웃 하단에 Disqus 나오게 만들어주세요.

**Comment by hcnoh** [comment]
알겠습니다.

**Comment by mino-park7** [comment]
- closed by pull request #21

**Comment by mino-park7** [comment]
disqus 오류발생으로 댓글창 켜지지 않네요... 이슈 리오픈 하겠습니다

**Comment by mino-park7** [comment]
issue closed by pull request #25
