### ISSUE TITLE
Google 검색 결과에 블로그 나오도록 만들기

### ISSUE THREAD

**Issue by mino-park7** [tmaxai/tmaxai.github.io#16]

**Comment by mino-park7** [comment]
- _config.yml에 baseurl 등록이 안되있어서 sitemap.xml 이 제대로 동작하지 않음

**Comment by jeonghonah** [comment]
이거 구현된 건가요?

**Comment by mino-park7** [comment]
네 post 내용들 검색하면 나옵니다

**Comment by mino-park7** [comment]
google search console에서 검색어 등 결과가 나오는 게 며칠 걸리므로 결과 확인하면 issue close 하도록 하겠습니다.

**Comment by mino-park7** [comment]
다시 또 검색이 안되는 것처럼 보이네요... 확인해보겠습니다

**Comment by ssunno** [comment]
검색 엔진에 반영되는게 시간이 꽤 걸리는 일이라 바로 확인이 어렵겠네요

**Comment by jeonghonah** [comment]
며칠 지났는데 아직 구글에서 검색이 안 걸리는 군요

**Comment by mino-park7** [comment]
![image](https://user-images.githubusercontent.com/33409967/52022965-9173db80-253e-11e9-8386-5259a7096195.png)
이렇게 클릭수는 나오는데.... 무슨 문제일까요
포스트 수가 너무 적어서 그런가....

**Comment by mino-park7** [comment]
sitemap.xml url문제 해결 했습니다.
@jeonghonah @ssunno @Seungkeol-Kim google search console 관리자 기능 추가시켜드렸습니다.

**Comment by mino-park7** [comment]
구글에서 검색 되는 것 확인했습니다. 다만 게재 순위가 굉장히 낮네요... 포스트 수가 많아지면 해결 될 것으로 보입니다.

**Comment by mino-park7** [comment]
이슈 close 하겠습니다.
