### ISSUE TITLE
analytics.html 경로 오류로 빌드 실패

### ISSUE THREAD

**Issue by ssunno** [tmaxai/tmaxai.github.io#18]
default.html 파일에 포함된 analytics.html을 보면 analytics.html가 _include 폴더에 있어야 하는데 _layout에 있어서 빌드가 안된다고 하네요

아래는 관련 메시지:

> he page build failed for the `master` branch with the following error:
A file was included in `/_layouts/default.html` that is a symlink or does not exist in your `_includes` directory. For more information, see https://help.github.com/articles/page-build-failed-file-is-a-symlink/.

**Comment by mino-park7** [comment]
완료 했습니다
