### ISSUE TITLE
내부 검색 기능

### ISSUE THREAD

**Issue by jeonghonah** [tmaxai/tmaxai.github.io#23]
github.io 기반 위키를 보면 검색 기능이 있었던 것 같은데, 우리도 구글 말고 검색을 넣을 수 있을까요?

**Comment by mino-park7** [comment]
https://github.com/christian-fei/Simple-Jekyll-Search
이런게 있네요

**Comment by hojin-kim** [comment]
저 이거 해보고 있는데 하루이틀 더 걸릴 것 같습니다. 
말씀해주신 Simple-Jekyll-Search 는 제목만 인덱싱하는 거라 본문 검색이 안 돼서 본문 검색이 되는 방법을 찾아서 해보고 있습니다.
