### ISSUE TITLE
about 페이지에 2실 연구주제 나열 및 큰 그림 넣기

### ISSUE THREAD

**Issue by jeonghonah** [tmaxai/tmaxai.github.io#26]
우리 워크샵 자료 만들었던거 정리해서 넣으면 좋겠네요.

**Comment by jeonghonah** [comment]
초안 완료.

**Comment by mino-park7** [comment]
NLP쪽 그림은 음성 시스템 그림입니다. NLP 기술 다 들어간 그림은
![image](https://user-images.githubusercontent.com/33409967/52023123-41e1df80-253f-11e9-9d31-0d00df1ef140.png)
이 그림입니다.
