### ISSUE TITLE
깃허브 업로드 시 _site 폴더 포함 안되게하기

### ISSUE THREAD

**Issue by ssunno** [tmaxai/tmaxai.github.io#28]
_site 파일이 jekyll이 만들어내는거라서 로컬에서 테스트하면 localhost:~~~~ 이런식으로 주소가 바뀌게 됩니다.

깃에 업로드하면 Pages 엔진이 다시 _site를 생성하기 때문에 _site를 업로드 하는게 의미 없는데 테스트 할때마다 새 파일이 생성되어서 깃허브에 올릴때 수십개씩 업로드되네요 

.gitignore에 추가 하는게 좋겠음.

**Comment by mino-park7** [comment]
jekyll serve하고나서 git add -A 하지 말고, git stash 하는 방법을 쓰긴 했었는데, .gitignore하는게 낫긴 하겠네요

**Comment by mino-park7** [comment]
이 이슈는 한건수 연구원한테 assign 시키겠습니다

**Comment by mino-park7** [comment]
@robinsongh381 (한건수) 연구원님. 해당 사항에 대해서 브랜치 따로 따서 pull request 날려주세요

**Comment by robinsongh381** [comment]
네 알겠습니다
