### ISSUE TITLE
favicon 달아주세요!

### ISSUE THREAD

**Issue by jeonghonah** [tmaxai/tmaxai.github.io#32]
있으면 크롬에서 탭구분할 때 도움이 될 것 같습니다. 제가 브라우저에 열린 탭이 많아서요.

**Comment by jeonghonah** [comment]
첫페이지는 파비콘이 나오네요. 나머지도 나오면 좋을 것 같아요!

**Comment by ssunno** [comment]
제가 달았는데, 파비콘 위치가 하드코딩으로 박혀있어서 메인페이지만 수정되는 것 같습니다. 제가 고치겠습니다

**Comment by jeonghonah** [comment]
_config.yml 파일에 파비콘 경로가 상대경로 박혀있었군요. 수정했습니다.
