### ISSUE TITLE
ABOUT 페이지에서 이미지 확대되지 않는 문제

### ISSUE THREAD

**Issue by ssunno** [tmaxai/tmaxai.github.io#34]
이미지 클릭하면 확대되는 기능이 about 페이지에서는 동작하지 않네요.
수정 필요함

**Comment by usik** [comment]
확인해보니 library는 있는데 이미지 클릭할때 event로 넘겨주는 js function이 필요합니다. 추가해서 테스트 후 올리겠습니다.

**Comment by usik** [comment]
궁금한게 있습니다. 
assets/lib 디렉토리에서 index.js 파일에서
$('.post > p > img[alt]').replaceWith(function () {
...
});
혹시 .post 페이지, about 페이지 말고 또 이미지를 확대하는 페이지가 있을까요?
저기서 .post -> .[page_class_name] 으로 바꾸면 되더라구요.
