### ISSUE TITLE
모바일 화면에서 navigation bar 크기가 조절되지 않는 문제

### ISSUE THREAD

**Issue by ssunno** [tmaxai/tmaxai.github.io#35]
navigation이 화면에 따라 크기가 조절되지 않습니다. 
@Seungkeol-Kim  페이지 가로길이 조정하면서 같이 하시면 좋을듯.

**Comment by jeonghonah** [comment]
승걸 팀장님 빨리 잡아주세요!

**Comment by Seungkeol-Kim** [comment]
4번이슈 page width 적용 후 어떻게 보이는지 같이 보고 진행하도록 하겠습니다.

**Comment by Seungkeol-Kim** [comment]
4번이슈 수정하면서 네비게이션바도 같이 수정했는데 모바일에서 잘 줄어드네요.
근데 옆으로 살짝 스크롤이 생기긴 합니다.
이것도 수정할까요? 아님 이정도는 내비둘까요?

**Comment by ssunno** [comment]
디자인 재설계 예정
