### ISSUE TITLE
페이지 가로 길이 늘리기

### ISSUE THREAD

**Issue by ssunno** [tmaxai/tmaxai.github.io#4]
가로 길이가 너무 좁게설정되어잇는 것 같음.

1단 페이지 형태이므로 가로 길이를 좀 더 늘리는 방향으로 변경 필요(또는 반응형)

**Comment by ssunno** [comment]
가로길이 최대치 정하고 그 이하는 반응형으로 만드는게 좋을 것 같습니다 ?

**Comment by mino-park7** [comment]
jekyll bootstrap 쓰면 되려나요?

**Comment by ssunno** [comment]
레이아웃에서 가로길이 설정에서도 할 수 있을걸요? 옛날에 해본거라 기억은 안나지만...

**Comment by Seungkeol-Kim** [comment]
issue04-page_width 브랜치에서 수정, 로컬 테스트시 옆으로 잘 늘어나서 보임.
창 사이즈 수정해도 알아서 잘 바뀜.
모바일에서 버튼들이 창을 뚫고 나가서 옆으로 길게 나열되지 않을까 예상됨.
일단 적용 후 모바일에서 어떻게 보이는지 확인 후 메뉴 버튼들의 줄 자동 바꾸기를 이슈 하나 새로 파서 진행함이 어떨까 합니다.

**Comment by Seungkeol-Kim** [comment]
정상작동 확인했습니다. 이슈 닫을게요.

**Comment by Seungkeol-Kim** [comment]
max 1000으로 바꾸게 reopen

**Comment by mino-park7** [comment]
#60 이거 하면서 페이지 다시 옆으로 늘어진 것 같아요

**Comment by Seungkeol-Kim** [comment]
어 여기다 달아놨었네.. #66에서 진행하겠습니다.
