### ISSUE TITLE
category, tag 정책 결정 및 해당 내용을 문서에 기록

### ISSUE THREAD

**Issue by jeonghonah** [tmaxai/tmaxai.github.io#40]
내용, 대상 독자 수준을 고려하여 태그를 달도록 관련 정책을 다듬으면 좋을 것 같아요.

난이도 : 초, 중, 고급
주제 : Review, TmaxTD (티맥스 기술), TmaxProduct (제품)...
서브주제 : Industry, Vision, NLP
세부주제 : Attention, Intent classification, AI-ET... (자유롭게)

이정도로 정리하면 되지 않을까요? 이 내용을 정리해서 CONTRIBUTION.md에 업데이트하고 전체 공지해주시면 좋겠어요.

**Comment by ssunno** [comment]
타사 블로그 보면

lunit 에서는 카테고리를 tutorial, paper review, original research로 나누고 있네요.(태그없음)
카카오에서는 태그만 사용하고 있습니다.

**Comment by ssunno** [comment]
난이도or주제를 기준으로 카테고리를 정하고, 세부 주제를 tag로 사용하는게 어떨까요 ?

**Comment by jeonghonah** [comment]
태그로도 다 가능할 것 같긴한데, 우리는 둘다 쓰면 좋겠네요. 

카테고리 : tutorial, paper review, original research
태그 : 난이도(초급, 중급, 고급), 세부 주제(NLP, Vision, Attention, Intent classification, AI-ET)

**Comment by jeonghonah** [comment]
> 난이도or주제를 기준으로 카테고리를 정하고, 세부 주제를 tag로 사용하는게 어떨까요 ?
> 
> 태그는 가급적 외부인이 보는 것을 기준으로 정하는게 좋을 것 같습니다. 사내에서 부르는 용어보다는 알려진 연구분야(Face Recognition, Attention, Residual Net 등)를 선택하도록 가이드 해야할 것 같네요

카테고리를 여러 개 할 수 있나요..?

**Comment by ssunno** [comment]
> > 난이도or주제를 기준으로 카테고리를 정하고, 세부 주제를 tag로 사용하는게 어떨까요 ?
> > 태그는 가급적 외부인이 보는 것을 기준으로 정하는게 좋을 것 같습니다. 사내에서 부르는 용어보다는 알려진 연구분야(Face Recognition, Attention, Residual Net 등)를 선택하도록 가이드 해야할 것 같네요
> 
> 카테고리를 여러 개 할 수 있나요..?

네 카테고리도 여러 개 설정할 수 있습니다.

**Comment by jeonghonah** [comment]
어떤 방향으로든 일관되기만 하면 상관없겠어요. 누군가에게 assign만 잘 해주세요 ㅎㅎ

**Comment by jeonghonah** [comment]
contribuing.md는 원래 컨트리뷰터 나열하는 용도 아닌가요..?

**Comment by ssunno** [comment]
> contribuing.md는 원래 컨트리뷰터 나열하는 용도 아닌가요..?

https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md

다른 프로젝트들 보니 CONTRIBUTING.md 프로젝트 가이드에 관해서 쓰는 곳이네요. 목적상 CONTRIBUTING.md가 맞아보입니다.

**Comment by ssunno** [comment]
#42 이슈와 함께 정리하겠습니다. @Mincheol-Cha 제가 작성하는 가이드라인 문서에 붙이시면 됩니다

**Comment by Mincheol-Cha** [comment]
@ssunno @jeonghonah 휴가 다녀와서 지금 봤네요ㅠ 정리해보도록 하겠습니다!

**Comment by Mincheol-Cha** [comment]
@jeonghonah @ssunno #42 카테고리, 태그 결정 사항 가이드라인 문서에 붙여 작성 완료하였습니다!

수정사항 보이시면 알려주시면 감사하겠습니다 :)

**Comment by ssunno** [comment]
Issue #42 에서 작업 이어서 진행하겠습니다.
