### ISSUE TITLE
Preview에서 markdown 변환된걸 볼 수 있을까요?

### ISSUE THREAD

**Issue by hyunsuky** [tmaxai/tmaxai.github.io#41]
블로그 포스팅 하려고 하는데 preview에서 마크다운 변환된게 보이지 않습니다.
테스트 할 수 있게 변환된걸 볼 수 있는 기능을 추가해 주셨으면 좋겠습니다.

**Comment by ssunno** [comment]
현재는 개인 PC에 Jekyll 설치해서 적용되는 모습을 테스트 해 볼 수 있기는 한데 ....

깃허브에는 실제로 운영되는 블로그에 들어갈 완성된 자료만 업로드해야하니 테스트를 위한 서버를 따로 만들거나 어떤 방법이 있어야겟네요.

**Comment by jeonghonah** [comment]
선로 팀장님 의견처럼 ruby 깔아서 jekyll 로컬 서버 돌려보는게 제일 확실할 거고,
프렉티컬 하게는 브랜치하나 새로 딴 다음에 커밋해서 깃헙 소스 탐색으로 열어보면 될 것 같습니다.

**Comment by jeonghonah** [comment]
로컬에서 띄워 봤는데 별 문제없이 잘 되네요.

http://192.2.20.1:4000/about/

**Comment by jeonghonah** [comment]
> > 로컬에서 띄워 봤는데 별 문제없이 잘 되네요.
> > http://192.2.20.1:4000/about/
> 
> 기능 추가/개선이나 post 작성시 master에 올려서 봐야한다는 점이 안좋을 것 같네요. 각자 로컬에서 환경 구성하거나 서버가 있으면 좋을텐데, 내부망 서버 사용시 외부망or회사 밖에서는 작업이 어렵게 되겠네요

루비 정도는 집 pc나 노트북으로 로컬에서 각자 띄워도 되죠. 10분이면 되요.
git으로 버전 관리하는 것도 이런게 장점이기도 하구요.

**Comment by jeonghonah** [comment]
브랜치 따서하는 건 { } 변수같은거 처리안 되는거 말고 무슨 문제가 있죠?

**Comment by hyunsuky** [comment]
> > > 로컬에서 띄워 봤는데 별 문제없이 잘 되네요.
> > > http://192.2.20.1:4000/about/
> > 
> > 
> > 기능 추가/개선이나 post 작성시 master에 올려서 봐야한다는 점이 안좋을 것 같네요. 각자 로컬에서 환경 구성하거나 서버가 있으면 좋을텐데, 내부망 서버 사용시 외부망or회사 밖에서는 작업이 어렵게 되겠네요
> 
> 루비 정도는 집 pc나 노트북으로 로컬에서 각자 띄워도 되죠. 10분이면 되요.
> git으로 버전 관리하는 것도 이런게 장
