### ISSUE TITLE
로컬에서 블로그 수정사항 테스트하는 방법 가이드라인 작성

### ISSUE THREAD

**Issue by ssunno** [tmaxai/tmaxai.github.io#42]
실 인원들이 로컬에서 테스트 할 수 있게 가이드문서가 필요할 것 같습니다.

**Comment by mino-park7** [comment]
이건 선로 팀장님이 작성해주시죠 관리왕 rail lee

**Comment by jeonghonah** [comment]
그림 올릴 때도 가이드가 필요할 것 같아요. 위아래 빈줄 넣어야 제대로 동작하네요.
물론 항상 잘되도록 바꾸면 더 좋긴 할 텐데, 괜히 시간 낭비일 듯요.

https://github.com/tmaxai/tmaxai.github.io/issues/50

**Comment by mino-park7** [comment]
iframe youtube 관련 사항 @y-rok 님이 pr한거 #53
이거 관련해서도 가이드 추가해야할듯해요

**Comment by Mincheol-Cha** [comment]
#40 Category, Tag 관련 조사 및 정책 결정 사항

##### 타사 기술 블로그 Category, Tag 현황  
* 우아한 형제들 기술 블로그: 
- Categories: Study, Experience, Tools 등 10개의 카테고리
- Tag: 해당사항 없음
* 카카오 Tech:
- Categories: 기술 블로그 내 따로 카테고리는 없고 블로그, 오픈소스, 오픈API, 기술행사 등을 독립적으로 나누었음.
- Tag: kakao, ai, cnn, deep-learning, coding 등의 수많은 태그 존재
* Instagram Engineering:
- Categories: Machine Learning, Android, IOS, Infrastructure, Data, Open Source로 나누었음.
- Tag: 카테고리 안에서의 문서들은 모두 그 카테고리 이름을 태그로 사용
* Line Engineering:
- Categories: Back-End, Front-End, Games, Miscellaneous, Security로 나눔
- Tag: Advent Calendar, chatbot, LINE BOT, Homework 등의 수많은 태그 존재
* 네이버 D2:
- Categories: 세부 카테고리는 없고 Hello World라는 네이버 개발자들이 직접 정리한 실전 개발 경험과 지식이 담겨진 블로그. D2 News라는 개발자 행사 소식과 산출물 공유하는 것으로 나눔
- Tag: 블로그 글들의 제목의 핵심 키워드를 태그로 선정
* Lunit Tech Blog:
- Categories:Original Research, Paper Review, Tutorial로 나누었음.
- Tag: 태그는 존재하지 않음

**Comment by Mincheol-Cha** [comment]
#40 Category, Tag 관련 조사 및 정책 결정 사항
### 티맥스 AI 기술 블로그 Category, Tag 정책 사항

#### Categories: 
* Tmax AI Research: 각 팀에서 연구하는 주제와 직접적인 밀접한 관련이 있는 논문들에 대한 포스팅(ex 1팀: Anomaly detection 관련 논문 포스팅 2팀: 얼굴인식. traffic 관련 논문 포스팅, 3팀: NLP 관련 논문 포스팅)
* Paper Review: AI와 관련된 비교적 최신의 흥미로운 논문들에 대한 포스팅
* Tutorial: 비교적 잘 알려진 연구 주제 or 네트워크에 관한 본인만의 내용 정리가 담긴 포스팅

#### Tag
* 주제: CNN, RNN, LSTM, Autoencoder, Representation Learning 등의 큰 주제를 태그로 달기 
* 세부 주제: Attention, Intent Classification, AI-ET, Calibration과 같은 세부 주제들을 태그로 달기
* Keyword: 포스팅한 글의 제목이나 내용 중에서 핵심 키워드를 정리하여 태그로 달기
* 난이도: 초급, 중급, 고급 중 포스팅하는 연구원이 판단한 난이도 태그로 달기

#### 더 나은 건의 사항이나 수정 사항있으면 답글 부탁드립나다 :)

**Comment by ssunno** [comment]
> #40 Category, Tag 관련 조사 및 정책 결정 사항
> 
> ### 티맥스 AI 기술 블로그 Category, Tag 정책 사항
> #### Categories:
> * Tmax AI Research: 각 팀에서 연구하는 주제와 직접적인 밀접한 관련이 있는 논문들에 대한 포스팅(ex 1팀: Anomaly detection 관련 논문 포스팅 2팀: 얼굴인식. traffic 관련 논문 포스팅, 3팀: NLP 관련 논문 포스팅)
> * Paper Review: AI와 관련된 비교적 최신의 흥미로운 논문들에 대한 포스팅
> * Tutorial: 비교적 잘 알려진 연구 주제 or 네트워크에 관한 본인만의 내용 정리가 담긴 포스팅
> 
> #### Tag
> * 주제: CNN, RNN, LSTM, Autoencoder, Representation Learning 등의 큰 주제를 태그로 달기
> * 세부 주제: Attention, Intent Classification, AI-ET, Calibration과 같은 세부 주제들을 태그로 달기
> * Keyword: 포스팅한 글의 제목이나 내용 중에서 핵심 키워드를 정리하여 태그로 달기
> * 난이도: 초급, 중급, 고급 중 포스팅하는 연구원이 판단한 난이도 태그로 달기
> 
> #### 더 나은 건의 사항이나 수정 사항 있으면 답글 부탁드립나다 :)

`Paper Review`와 `Tmax AI Research`가 많이 겹칠 것 같네요(주로 연구와 관련된걸 읽기 때문에). 그리고 페이퍼가 아닌 것도 리뷰하는 경우가 있을 것 같기도 한데(알파고 같은 경우) 카테고리 약간 고민 필요해보입니다

**Comment by jeonghonah** [comment]
수고하셨습니다.
