### ISSUE TITLE
그림이 글 밖으로 나가는 오류

### ISSUE THREAD

**Issue by hyunsuky** [tmaxai/tmaxai.github.io#50]
그림을 첨부했을 때 글이랑 align되어 있지 않고 밖으로 나가게 표시됩니다.
문단 간격에 맞게 그림을 resize시킬 수 있는 기능이 필요한 것 같습니다.

**Comment by hyunsuky** [comment]
![photo_2019-02-03_16-57-48](https://user-images.githubusercontent.com/37831864/52174369-057be100-27d6-11e9-837c-706445e6391b.jpg)

**Comment by jeonghonah** [comment]
그림 태그를 넣을 때 위아래로 빈줄을 하나씩 넣어주면 올바르게 작동하네요.
클릭하면 확대되는 기능도 마찬가지로 빈줄이 필요합니다.

<<빈줄>>
![AUC](/assets/img/2019-02-01-Ng-CheXNeXt/AUC.PNG)
<<빈줄>>

이유는 아마도 아래 때문일 것 같습니다.

1. main.css에서 #main p img { width : 100% }으로 정의됨.
2. index.js에서 jquery로 img 태그를 찾을 때 ".post > p > img"로 하드코딩.

**Comment by hyunsuky** [comment]
감사합니다 실장님! 그림 크기 잘 조절되는 것 확인하였습니다.
