### ISSUE TITLE
authors.yml에 작성자 정보 추가

### ISSUE THREAD

**Issue by mino-park7** [tmaxai/tmaxai.github.io#54]
댓글로 달아주세요

mino-park7:
    name: Minho Park
    email: minho.park2115@gmail.com

**Comment by junkeon** [comment]
jkpark:
name: JunKeon Park
email: [palex3012@gmail.com](mailto:palex3012@gmail.com)

**Comment by ssunno** [comment]
ssunno:
name: Sun Ro Lee
email: lsn3192@gmail.com

**Comment by hojin-kim** [comment]
hojin-kim:
    name: Hojin Kim 
    email: hojink.kim@gmail.com

**Comment by hcnoh** [comment]
hcnoh:
name: Hyungcheol Noh
email: rhc0624@gmail.com

**Comment by jeonghonah** [comment]
jeonghonah
name: Jeongho Nah
email: jeongho.nah@gmail.com

**Comment by SeoJaeMin** [comment]
jaemin:
name: Jaemin Seo
email: onlytjwo@naver.com

**Comment by horang2k** [comment]
horang2k
name: Jongho Lee
email: [horang2k@gmail.com](mailto:horang2k@gmail.com)

**Comment by usik** [comment]
usik
name: Yu Sik Kim
email: usik.o2@gmail.com

**Comment by BroCoLySTyLe** [comment]
BroCoLySTyLe
name: Byounggeon Kim
email: kbg5213@gmail.com

**Comment by yhyoon18** [comment]
yhyoon18
name: Yeo Hun Yoon
email: yhyoon93@gmail.com

**Comment by MoongMoong** [comment]
moongmoong
name: Jaeseok Kim
email: b2ird21@kaist.ac.kr

**Comment by Mincheol-Cha** [comment]
Mincheol-Cha
name: Mincheol Cha
email: chamchur@gmail.com

**Comment by seokmin-kim** [comment]
seokmin-kim
name: Seokmin Kim
email : seokmin_kim@tmax.co.kr

**Comment by robinsongh381** [comment]
robinsongh381
name: Gunsoo Han
email: robinsongh381@gmail.com

**Comment by Seungkeol-Kim** [comment]
azzibobjo
name : seungkeol kim
emil : seungkeol_kim@tmax.co.kr

**Comment by y-rok** [comment]
y-rok
name: Youngrok Jang
email: youngrok_jang@tmax.co.kr

**Comment by mino-park7** [comment]
@jhlee0427 @LaPlumeNoire 휴가 다녀오시면 정보 추가 부탁드립니다

**Comment by LaPlumeNoire** [comment]
LaPlumeNoire
name: Wonyl Choi
email: wonyl_choi2@tmax.co.kr

**Comment by mino-park7** [comment]
@jhlee0427 확인 부탁 드려요

**Comment by jhlee0427** [comment]
jhlee0427
name: Joohan Lee
email: joohannnnn@gmail.com

**Comment by mino-park7** [comment]
완료했습니다 이슈 클로즈하겠습니다
