### ISSUE TITLE
index 페이지 summary 뒤에 category, tag 출력

### ISSUE THREAD

**Issue by jeonghonah** [tmaxai/tmaxai.github.io#57]
카테고리, 태그가 함께 나오면 좀더 보기 좋을 것 같아요!

**Comment by mino-park7** [comment]
제 블로그 테마는 태그가 붙어 있네요.
https://github.com/mino-park7/mino-park7.github.io/blob/master/blog/index.html
이거 확인해 보시면 좋을 것 같아요 to @BroCoLySTyLe

**Comment by hyunsuky** [comment]
지금 index와 main article width 조절이 필요한 상태인 것 같습니다. 구글 AI blog (https://ai.googleblog.com/)나 Lunit tech blog (https://blog.lunit.io/)를 참고해서 작업하는게 어떨지요.

**Comment by mino-park7** [comment]
> 지금 index와 main article width 조절이 필요한 상태인 것 같습니다. 구글 AI blog ([https://ai.googleblog.com/)나](https://ai.googleblog.com/)%EB%82%98) Lunit tech blog ([https://blog.lunit.io/)를](https://blog.lunit.io/)%EB%A5%BC) 참고해서 작업하는게 어떨지요.

#60 에 리플라이 해주시는게 더 나아 보입니다

**Comment by ssunno** [comment]
디자인 재설계 예정
