### ISSUE TITLE
글 작성자 이름 표시하는 기능 추가

### ISSUE THREAD

**Issue by ssunno** [tmaxai/tmaxai.github.io#6]
누가 썻는지 볼 수 있게하기위해서, 글 작성자의 이름을 표시하는 기능을 추가하면 좋겠음.

github image 링크를 가져오거나, gravatar를 쓰거나, 그냥 github에 프로필 정보를 저장하거나 하는 식으로 방식은 많은데 적당한걸 고르면 좋겠음.

YAML의 writer 정보를 입력하도록 가이드 했으므로 여기에 writer 정보를 활용해서 매칭하는 방식으로 구현하는게 좋겠음.

**Comment by jeonghonah** [comment]
이건 꼭 있어야할 것 같아요

**Comment by ssunno** [comment]
https://tech.kakao.com

**Comment by mino-park7** [comment]
https://github.com/kakao/kakao.github.io
여기에 설명이 잘 되어 있네요

**Comment by ssunno** [comment]
이슈 담당자 바뀌면 관련자료도 수정해주세요. @Seungkeol-Kim 이거 유현석 연구원이 하고 있으시던데

**Comment by hyunsuky** [comment]
기능 추가하였습니다. _data/authors.yml에 들어가서 author information 추가하시고 author tag 달면 됩니다.

**Comment by mino-park7** [comment]
pr 내용 보니깐 post.html에서만 author 내용 추가되는 것 같은데, index.html에서 author 내용 추가 시키는 기능도 필요 할 것 같아요 위에 https://tech.kakao.com 처럼

**Comment by hyunsuky** [comment]
Index.html에도 author가 표시되는 기능이 추가되었습니다.

**Comment by hyunsuky** [comment]
![photo_2019-02-03_18-02-19](https://user-images.githubusercontent.com/37831864/52174954-2e54a400-27df-11e9-9498-29a73c9bc7c9.jpg)
