### ISSUE TITLE
포스트 제목 크기, 폰트 변경 및 미리보기 수준 변경

### ISSUE THREAD

**Issue by ssunno** [tmaxai/tmaxai.github.io#60]
메인화면에서 포스트 제목이 너무 커서 가시성이 떨어지는 것 같습니다. 제목이 긴 경우에 더 그런 것 같습니다.

1. 현재 제목 크기가 1.5em 으로 되어있는데 1.2em 정도로 줄이면 좋을 것 같음
2. 제목 폰트(Raleway)가 한글을 지원하지 않아서 한글로 제목이 작성되는 경우 서로 다른 폰트가 사용되어 보기에 좋지 않음. 한글/영어를 동시에 지원하는 폰트(Noto Sans 같은것)로 변경 필요
3. 메인화면에서 글 미리보기가 너무 조금 나오는 것 같음. 제목이 길면 제목보다도 더 조금나오는데 제목 크기를 줄이고 내용을 약간 더 보여주는게 좋지 않을까요?

**Comment by ssunno** [comment]
@mino-park7 글 미리보기 담당했던 분한테 어사인 해주시면 좋을 것 같습니다

**Comment by mino-park7** [comment]
#57과 함께 처리하면 되겠네요.
근데 미리보기 담당했던 분이 저입니다만....

**Comment by MoongMoong** [comment]
![2019-02-13 11-06-13](https://user-images.githubusercontent.com/26134358/52681545-7d3ccf00-2f7f-11e9-8f3b-a0132ca2bd5c.png)

@ssunno 
이런 식으로 수정해 보았는데 괜찮을까요?
1. 32px -> 22px
2. 제주고딕 폰트 적용
3. preview 글자 수를 1.5배로 증가

**Comment by mino-park7** [comment]
미리보기 수준이 안바뀐 것 같은데 확인 부탁드려요

**Comment by mino-park7** [comment]
그리고 폰트가 ubuntu와 mac에서 서로 다르게 보여요

**Comment by mino-park7** [comment]
일단 #70 로 #68 revert 시켰습니다. 다시 작업 부탁드려요

**Comment by mino-park7** [comment]
#71 로 수정되었습니다

**Comment by junkeon** [comment]
제목 폰트랑 폰트 사이즈가 예전꺼가 나은 거 같습니다
제목 폰트가 고딕이라 눈에 잘 안들어오고,  포스트 글에 비해 제목 폰트가 너무 작아서 포스트 글과 잘 구분되지 않습니다

**Comment by hyunsuky** [comment]
지금 index와 main article width 조절이 필요한 상태인 것 같습니다. 구글 AI blog (https://ai.googleblog.com/)나 Lunit tech blog (https://blog.lunit.io/)를 참고해서 작업하는게 어떨지요.
