### ISSUE TITLE
포스트의 표 구분자가 보이지 않음

### ISSUE THREAD

**Issue by junkeon** [tmaxai/tmaxai.github.io#64]
표를 작성하고 실행하면 행과 행 그리고 열과 열을 구분하는 선이 보이지 않습니다

깨져 보이는 것은 아닙니다

**Comment by junkeon** [comment]
표도 중앙 정렬이 되었으면 좋겠습니다

**Comment by ssunno** [comment]
@junkeon 관련 증상 좀더 자세히 알려주세요. 어디서 그런 문제가 있는지, 스크린샷이나 그런 것

**Comment by junkeon** [comment]
![image](https://user-images.githubusercontent.com/35945268/52615666-4f9d4a80-2ed9-11e9-9a9a-b1d661b006db.png)
여기 보면 각 셀들마다 가운데 정렬된 것도 확인할 수 있는데 열과 열 사이, 행과 행 사이에 구분선이 안 보입니다

**Comment by junkeon** [comment]
css에 표와 관련된 옵션 추가해서 해결했습니다

**Comment by mino-park7** [comment]
풀 리퀘스트 보냈나요?
