### ISSUE TITLE
블로그 포스트 폭이 너무 깁니다

### ISSUE THREAD

**Issue by junkeon** [tmaxai/tmaxai.github.io#66]
포스트의 폭이 너무 넓어서 한 눈에 보기 너무 힘듭니다

좌우 패딩을 주거나 하는 식으로 폭을 좀 줄여서 가독성을 높였으면 합니다

**Comment by jeonghonah** [comment]
#4 범인인것 같은데요

**Comment by ssunno** [comment]
최대 길이를 지정해서 넓은화면(모니터 등)에서 블로그가 너무 길어지지 않게 하는게 좋겠습니다.

**Comment by jeonghonah** [comment]
일단 css에 max-width 라도 넣으면 좋겠어요.

https://developer.mozilla.org/en-US/docs/Web/CSS/max-width

**Comment by Seungkeol-Kim** [comment]
오전에 0a1c2da449d1f98003a0dc0df3e3acfbe695cc74 커밋으로 길이 조절, max-length 등 설정, 정상 작동 확인했습니다.
#68 적용 커밋(e81f5e3f0edfcf7018b70fba99f135b50fbb128c) 이후 텍스트 영역 너비, 텍스트 얼라인 위치 등이 다 깨집니다.
로컬 롤백 후 테스트로 해당 커밋이 문제인거 확인했습니다.
수정하신분 확인 후 수정 부탁드립니다.

**Comment by Seungkeol-Kim** [comment]
글 폭 문제는 #68 리버트로 해결되었으니 close 하겠습니다.
제목, 폰트 등의 수정은 #68 reopen 혹은 신규 issue로 진행 부탁드립니다.
